version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update && apt-get install -y libpq-dev build-essential
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 758327527391.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ecr/ci-cd .
      - docker tag ecr/ci-cd:latest 758327527391.dkr.ecr.eu-north-1.amazonaws.com/ecr/ci-cd:latest

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push 758327527391.dkr.ecr.eu-north-1.amazonaws.com/ecr/ci-cd:latest || echo "Push failed"

      - echo "Publishing SNS Notification..."
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          MESSAGE="✅ Build SUCCEEDED: $CODEBUILD_BUILD_ID"
          SUBJECT="SUCCESS: $CODEBUILD_PROJECT_NAME"
        else
          MESSAGE="❌ Build FAILED: $CODEBUILD_BUILD_ID"
          SUBJECT="FAILURE: $CODEBUILD_PROJECT_NAME"
        fi
