version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update && apt-get install -y libpq-dev build-essential
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 758327527391.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ecr/ci-cd .
      - docker tag ecr/ci-cd:latest 758327527391.dkr.ecr.eu-north-1.amazonaws.com/ecr/ci-cd:latest

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push 758327527391.dkr.ecr.eu-north-1.amazonaws.com/ecr/ci-cd:latest

  finally:
    commands:
     # - echo "DEBUG: Build status code - $CODEBUILD_BUILD_SUCCEEDING"
      - >
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then
          MESSAGE="SUCCESS ✅ $CODEBUILD_BUILD_ID";
        else
          MESSAGE="FAILURE ❌ $CODEBUILD_BUILD_ID";
        fi;
        echo "Publishing to SNS...";
        aws sns publish \
          --topic-arn arn:aws:sns:eu-north-1:758327527391:CodeBuildNotifications \
          --message "$MESSAGE" \
          --subject "[$CODEBUILD_BUILD_SUCCEEDING] Build Status" \
          --region eu-north-1 \
          2> sns-error.log || echo "SNS publish failed!";
      - echo "SNS Error Logs:"
      - cat sns-error.log
      
