apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3  # Number of app replicas (you can auto-scale later)
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "869700439509.dkr.ecr.eu-north-1.amazonaws.com/kavitha/repo:latest"
        ports:
        - containerPort: 5000

