apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3  # Number of app replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "869700439509.dkr.ecr.eu-north-1.amazonaws.com/kavitha/repo:latest"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"  # Minimum memory for the container
            cpu: "250m"     # Minimum CPU for the container
          limits:
            memory: "1.5Gi"  # Maximum memory for the container
            cpu: "500m"      # Maximum CPU for the container
