apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "869700439509.dkr.ecr.eu-north-1.amazonaws.com/kavitha/repo:latest"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: "13.50.248.202"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "db1"
        - name: DB_USER
          value: "sai"
        - name: DB_PASSWORD
          value: "Sai@2024"
